version: '3.9'

services:

  api:
    container_name: nfe-xml-validator-api
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
    networks:
      - backend

networks:
  backend:
    name: backend