version: '3.9'

services:

  api:
    container_name: nfe-xml-validator-api
    image: tiagosaldanha/nfe-xml-validator-api:latest
    restart: always
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "5000:80"
    networks:
      - backend

networks:
  backend:
    name: backend
